name: 'music_and_marketing_audit'
version: '1.0.0'
config-version: 2

profile: 'music_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  music_and_marketing_audit:
    bronze:
      schema: bronze
      materialized: table